### ISSUE TITLE
Not possible to use it as descriped in Laravel 7

### ISSUE THREAD

**Issue by ricklambrechts** [petercoles/Multilingual-Country-List#10]
Today i was trying this package out.

As described i was using:
`Countries::lookup();`

But Countries cannot be found.

Because it is a singleton it is possible to do this but it would be nice to use the above method.
`$countries_provider = app('countries');`
`$countries = $countries_provider->lookup('nl_NL');` 

Is this an issue of the package?

**Comment by petercoles** [comment]
Works fine for me in Laravel 7. How are you loading the Countries facade? E.g. `use Countries;`

**Comment by ricklambrechts** [comment]
When i use `Countries::lookup();` the IDE (PHPStorm) is telling me Undefined class.
And when i use `use Countries;` on top, then is laravel telling me 'Call to undefined method PeterColes\Countries\Maker::all()' on the error page.

**Comment by petercoles** [comment]
You certainly need a use statement to load the facade, otherwise it's right for it to be reported as undefined.

The undefined method all() is very curious. There's nothing in the package that attempts to call an `all()` method. and `Countries::lookup()` is mapped to `PeterColes\Countries\Maker::lookup()`, which does exist, so doesn't throw an error.

Can you provide a gist for the entire file where you are making your call?

**Comment by ricklambrechts** [comment]
Sorry, my fault when i use it like this. It is working.
`use Countries;`
`$countries = Countries::lookup();`

But the IDE is not recognizing the class. Maybe i should use the Laravel IDE Helper Generator. 

Thanks for the fast response!
